### ISSUE TITLE
▫️◽️◻️Role Building Checklist◻️◽️▫️

### ISSUE THREAD

**Issue by Cdaprod** [Cdaprod/BugBounty-Infrastructure#5]
### Ansible Role Checklist

This checklist outlines the necessary files for each Ansible role. 

#### Attack Server Role

- [x] `attack/tasks/main.yml`: Main tasks file for the attack server.
- [ ] `attack/vars/main.yml`: Variables for the attack server.
- [ ] `attack/handlers/main.yml`: Handlers for the attack server.
- [ ] `attack/templates/`: Any necessary templates for the attack server.
- [ ] `attack/files/`: Any necessary files for the attack server.
- [ ] `attack/meta/main.yml`: Metadata for the attack server role.

#### Database Server Role

- [ ] `database/tasks/main.yml`: Main tasks file for the database server.
- [ ] `database/vars/main.yml`: Variables for the database server.
- [ ] `database/handlers/main.yml`: Handlers for the database server.
- [ ] `database/templates/`: Any necessary templates for the database server.
- [ ] `database/files/`: Any necessary files for the database server.
- [ ] `database/meta/main.yml`: Metadata for the database server role.

#### Proxy Server Role

- [ ] `proxy/tasks/main.yml`: Main tasks file for the proxy server.
- [ ] `proxy/vars/main.yml`: Variables for the proxy server.
- [ ] `proxy/handlers/main.yml`: Handlers for the proxy server.
- [ ] `proxy/templates/`: Any necessary templates for the proxy server.
- [ ] `proxy/files/`: Any necessary files for the proxy server.
- [ ] `proxy/meta/main.yml`: Metadata for the proxy server role.
